on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Reease

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all --check
      - run: cargo doc

  test:
    needs:
      - checks
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  publish:
    needs:
      - checks
      - test
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
